'use client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

const queryClient = new QueryClient();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Toaster />
          <Navbar />
          <div className='min-h-screen'>
            {children}
          </div>
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  )
}
